config/routes.rb
Rails.application.routes.draw do
  get 'rentings/create'
  devise_for :users, :controllers => { registrations: :registrations }
  # localhost3000/
  root to: 'dogs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # profile page for the users (owners and renters) ???
  get 'dashboard', to:'pages#dashboard'
  get 'dashboard/edit', to: "pages#dashboard_edit"
  # CRUD
  resources :dogs do
  # If only there is a dog you could rent
    resources :rentings, only: :create

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many :rentings
  belongs_to :user
  validates :name, :age, :breed, :price, :location, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  mount_uploader :image, ImageUploader

  def unavailable_dates
    rentings.pluck(:start, :end).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/renting.rb
class Renting < ApplicationRecord
  belongs_to :user
  belongs_to :dog
  validates :total_price, :start, :end, presence: true

  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if self.end.blank? || self.start.blank?

    if self.end < self.start
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :renting
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  # if there is no user(owner and renter) destroy the dog
  has_many :dogs, dependent: :destroy
  has_many :rentings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # [...]
  include Pundit

  # Pundit: white-list approach.

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :location])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :location, :description, :image, :name])
  end

  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end


end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  # call the method set_dog before selected actions
  before_action :set_dog, only: [:show, :edit, :update, :destroy]
  # No need to be logged-in
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # Read all dogs
    @max = Dog.all.sort_by { |d| d.price }.last.price
    @min = Dog.all.sort_by { |d| d.price }.first.price

    @dogs = Dog.all
    @user = current_user
    breed = params[:breed]
    age = params[:age]
    price = params[:price]
    location = params[:location]
    if breed && age && price
      @dogs = Dog.where(breed: breed, age: age).filter { |dog| dog.price < price.to_i }
    elsif breed && age && !price
      @dogs = Dog.where(age: age, breed: breed)
    elsif breed && price && !age
      @dogs = Dog.where(breed: breed).filter { |dog| dog.price < price.to_i }
    elsif price && age && !breed
      @dogs = Dog.where(age: age).filter { |dog| dog.price < price.to_i }
    elsif price
      @dogs = Dog.where('price >= ? AND price <=?', @min, price)
    elsif breed
      @dogs = Dog.where(breed: breed)
    elsif age
      @dogs = Dog.where(age: age)
    elsif location
      @dogs = Dog.where("location ILIKE ?", "%#{location}%")
    else
      @dogs = Dog.all
    end
    # if params[:breed].present?
    #   @dogs = Dog.where(breed: params[:breed])
    # elsif params[:age].present?
    #   @dogs = Dog.where(age: params[:age])
    # elsif params[:price].present?
    #   @dogs = Dog.where(price: params[:price])
    # else
    #   @dogs = Dog.all
    # end
  end

  def show
    # Read one dog
    # @dog = Dog.find(params[:id])
    # call the dog_policy method show
    authorize @dog
    @renting = Renting.new

    # returns flats with coordinates
    @dogs = Dog.geocoded
    @markers = @dogs.map do |dog|
      { lat: dog.latitude,
        lng: dog.longitude,
        infoWindow: render_to_string(partial: "location", locals: { dog: dog })}
    end
  end

  def new
    # opens an empty form
    @dog = Dog.new
    # calls the dog_policy method new
    authorize @dog
  end

  def create
    # Create a new instance with params
    @dog = Dog.new(dog_params)
    authorize @dog
    # Need to be logged-in to add dog listing
    @dog.user = current_user
    if @dog.save
      # Go to the show page of the created dog
      redirect_to dog_path(@dog)
    else
      render 'new'
    end
  end

  def edit
    # calls the dog_policy method edit
    authorize @dog
    # renders a form already with info to change
    # @dog = Dog.find(params[:id])

  end

  def update
    # Get the dog you want to edit
    # @dog = Dog.find(params[:id])
    # render the form with the info to update
    authorize @dog
    @dog.update(dog_params)
    # Go to the show page of the updated dog
    redirect_to dog_path(@dog)
  end

  def destroy
    authorize @dog
    # Get the dog you want to destroy
    # @dog = Dog.find(params[:id])
    # delete the dog
    @dog.destroy
    # Go to the user(owner) profile page(Dog listing)
    redirect_to dashboard_path
  end

  private

  def dog_params
    # white list
    params.require(:dog).permit(:name, :age, :breed, :location, :price, :image, :image_cache)
  end

  def set_dog
    @dog = Dog.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def dashboard
    @user = current_user
    @rentings = @user.rentings
    @dogs = @user.dogs
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

    def after_update_path_for(resource)
      dashboard_path
    end
end

app/controllers/rentings_controller.rb
class RentingsController < ApplicationController
  def create

    @renting = Renting.new(renting_params)
    @dog = Dog.find(params[:dog_id])
    authorize @dog
    @renting.dog = @dog
    @renting.user = current_user
    @renting.total_price = (@renting.end - @renting.start) / 86_400 * @dog.price

    if @renting.save
      redirect_to dashboard_path
    else
      render 'dogs/show'
    end
  end

  private

  def renting_params
    params.require(:renting).permit(:start, :end)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/_form.html.erb
<%= simple_form_for @dog do |f| %>
  <%= f.input :name %>
  <%= f.input :image %>
  <%= f.input :image_cache, as: :hidden %>
  <%= f.input :age %>
  <%= f.input :breed %>
  <%= f.input :price %>
  <%= f.input :location %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/dogs/_location.html.erb
<h2><%= dog.name %></h2>
<p><%= dog.location %></p>

app/views/dogs/_search_dog.html.erb
<%= form_tag dogs_path, method: :get, class: 'search_tabs' do %>

  <div class="d-flex">
    <div class="breed-dropdown mr-3">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2"
      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Breed</button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
        <% Dog.all.pluck(:breed).uniq.sort.each do |breed| %>
          <input class="checkbox" type="checkbox" name="breed[]" value="<%= breed %>" label="<%= breed %>"> <%= breed %> <br>
        <% end %>
      </div>
    </div>

    <div class="age-dropdown mr-3">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2"
      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Age</button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
          <% Dog.all.pluck(:age).uniq.sort.each do |age| %>
            <input class="checkbox" type="checkbox" name="age[]" value="<%= age %>" label="<%= age %>"> <%= age %> <br>
            <% end %>
        </div>
    </div>

    <div class="location">
      <%= text_field_tag :location, params[:location],
      class: "form-control", placeholder: "Location"%>
    </div>


    <div class="price-dropdown ml-3 d-flex align-items-center">
        <h1 class="mb-0">Price:&nbsp;</h1>

        <%= @min %>
        <input type="range" class="custom-range" name="price" min="<%= @min %>" max="<%= @max %>" id="price-range">
        <%#= @max %>
    <div class="d-flex justify-content-center" id="price-number">
    </div>
  </div>
  </div>

  <div class="submit-buttons">
    <%= submit_tag "Search", class: "btn btn-primary" %>
    <%= link_to 'Reset', root_path, class: 'button'  %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<%= render 'form', dog: @dog %>

app/views/dogs/index.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.25),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1523480717984-24cba35ae1ef?ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80);">
        <div class="homepage-card">
          <h1 class="text-left">Craving a companion?</h1>
          <%= link_to "Rent a Dog", "#all-dogs", class: "homepage-button align-item-left" %>
        </div>
      </div>
      </div>
      <div class="carousel-item">
        <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.25),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1550227384-d7b148fb3f50?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80);">
          <div class="homepage-card">
            <h1 class="text-left">Preoccupied with your job and your pup is left home alone?</h1>
            <!-- <div class="homepage-button align-item-left"> -->
             <%= link_to "Add a Dog", new_dog_path, class: "homepage-button align-item-left"%>
           <!-- </div> -->
         </div>
       </div>
     </div>
   </div>
   <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <div class="arrow bounce">
    <a class="fa fa-arrow-down fa-2x" href="#"></a>
  </div>
</div>

<div class="search-form-container mt-3">
  <%= render 'search_dog' %>
</div>
<div class="all-dogs-h1" id="all-dogs">
  <h1>All Dogs</h1>
  <div class="d-flex flex-wrap mx-5 mb-5 px-5 d-inline-flex p-2">
    <% @dogs.each do |dog| %>
    <div class="card-product">
      <%= cl_image_tag dog.image.url, height: 300, width: 400, crop: :fill %>
      <div class="card-product-infos">
        <%= link_to dog.name, dog_path(dog) %>
        <p>Age: <%= dog.age %></p>
        <p> $ <%=  dog.price %>/day</p>
      </div>
    </div>
    <% end %>
  </div>
</div>

<script>
  const priceNumber = document.querySelector("#price-number");
  const priceRange = document.querySelector("#price-range");
  priceRange.addEventListener("change", (event) => {
    priceNumber.innerHTML = "";
    priceNumber.insertAdjacentHTML("afterbegin", event.target.value);
  })
</script>

app/views/dogs/new.html.erb
<div class="container my-5">
  <h2>Add Dog Listing</h2>
  <%= render 'form', dog: @dog %>
</div>

app/views/dogs/show.html.erb
<div class = "container col-8 mt-5">

  <div class = "d-flex">
    <div class = "dog_image">
      <%= cl_image_tag @dog.image.url, height: 300, fill: 'sample'  %>
    </div>
      <div class = "dog_card ml-5">
          <h2><%= @dog.name %></h2>
          <li>Age: <%= @dog.age %></li>
          <li>Breed: <%= @dog.breed %></li>
          <li>Price: <%= @dog.price %></li>
          <li>Location: <%= @dog.location %></li>
          <li>Owner: <%= @dog.user.name %></li>

          <% if current_user == @dog.user %>
          <%= link_to "Edit this Dog", edit_dog_path(@dog), class: "btn btn-primary" %>
          <%= link_to "Delete this Dog", dog_path(@dog), method: :delete, class: "btn btn-primary" %>
          <% end %>

      </div>
  </div>
<h2 class="mt-5">Rent <%= @dog.name %></h2>
  <div id='dog-renting-dates' data-unavailable="<%= @dog.unavailable_dates.to_json %>">
    <% if user_signed_in? %>
      <% if current_user.id != @dog.user_id  %>
         <%= simple_form_for([@dog, @renting]) do |f| %>
             <%= f.input :start, as: :string, type: :text %>
             <%= f.input :end, as: :string, type: :text %>
             <%= f.submit "Book", class: "btn btn-primary" %>
          <% end %>
      <% end %>
    <% end %>
   </div>



  <h3>Location</h3>
  <div
  id="map"
  style="width: 100%;
  height: 400px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>

</div>

app/views/dogs/update.html.erb
<h1>Dogs#update</h1>
<p>Find me in app/views/dogs/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>PupHub</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= favicon_link_tag asset_path('dog.png') %>
  <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <%= render 'shared/navbar' %>
  <div class="overall-container">
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/pages/dashboard.html.erb
<div class="container my-5">
  <div class="d-flex flex-column bd-highlight mb-2">
    <div class="d-flex align-items-end flex-column bd-highlight mb-3" style="height: 80px;">
      <div class="p-2 bd-highlight"><p><%= link_to "Edit your profile", edit_user_registration_path, class: "btn btn-primary"%></p></div>
    </div>
    <div class="p-2 bd-highlight text-center">
      <% if @user.image? %>
      <img class="avatar-large" alt="avatar-large" src="<%= @user.image %>">
      <% else %>
      <img class="avatar-large" alt="avatar-large" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Circle-icons-profile.svg/1024px-Circle-icons-profile.svg.png">
      <% end %>
    </div>

    <div class="p-2 bd-highlight">
      <h2 class="card-description text-center">Hello, I'm <%=@user.name%></h2>
    </div>
    <div class="p-2 bd-highlight">
      <p class="card-description text-center">Joined in <%= @user.created_at.strftime("%Y") %> | From <%= @user.location%></p>
    </div>
  </div>
  <div class="container my-5 bg-white p-3" >
    <% if @user.description? %>
    <%= @user.description %>
    <% else %>
    <p>Add a description by editing your profile. It should include a little bit about yourself and your experience with dogs - so users know you better.</p>
    <% end %>
  </div>
  <div class="container my-5 bg-white p-3">
     <div class="d-flex align-items-end flex-column bd-highlight" style="height: 10px;">
        <div class="p-2 bd-highlight"><p> <%= link_to "Add your dog", new_dog_path, class: "btn btn-outline-secondary"  %></p></div>
    </div>
    <h3>My dogs</h3>

    <ul class="p-2 bd-highlight">
      <% @dogs.each do |dog| %>
      <li style="list-style-type:none"><i class="fas fa-paw"></i> <%= link_to dog.name, dog_path(dog) %></li>
      <% end %>
    </ul>
  </div>

  <div class="container my-5 bg-white p-3" >
    <div class="d-flex align-items-end flex-column bd-highlight" style="height: 10px;">
        <div class="p-2 bd-highlight"><p> <%= link_to "See all dogs", dogs_path, class: "btn btn-outline-secondary"  %></p></div>
    </div>
    <h3>Dogs you rented</h3>
    <ul class="p-2 bd-highlight">
      <% @rentings.each do |renting| %>
      <li style="list-style-type:none"><i class="fas fa-paw"></i> <%= link_to renting.dog.name, dog_path(renting.dog) %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rentings/create.html.erb
<h1>Rentings#create</h1>
<p>Find me in app/views/rentings/create.html.erb</p>

app/views/shared/_footer.html.erb
<footer>
   <div class="footer">
    <div class="footer-copyright" style="text-align: center;">
      <p>Copyright © 2019 DogHub <i class="fas fa-heart"></i> All rights reserved</p>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= 'navbar-home' if params[:controller] == "dogs" && params[:action] == "index" %>">
  <%= link_to dogs_path, class: "navbar-brand" do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/181/181867.svg", class: "svg" %>
    <p class="logo-name">PupHub</p>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if !user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Sign-up",  new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log-in", user_session_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item dropdown">

          <!-- <div class="p-2 bd-highlight text-center"> -->
            <% if current_user.image %>
              <%= image_tag current_user.image, alt: "alttext", class: 'avatar dropdown-toggle', id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <!-- <img class="avatar-large dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" alt="avatar-large" src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Circle-icons-profile.svg/1024px-Circle-icons-profile.svg.png"> -->
              <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Circle-icons-profile.svg/1024px-Circle-icons-profile.svg.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
          <!-- </div> -->

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item", id: "dropdown-logout" %>
            <%= link_to "See profile", dashboard_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>